### ISSUE TITLE
How to run the project

### ISSUE THREAD

**Issue by andodeki** [project-robius/moxin#17]
I run the project with this command
`MAKEPAD=lines sudo cargo +nightly run -p moxin-frontend --release`

and i get this error

> dyld[16218]: Library not loaded: @rpath/libwasmedge.0.dylib
  Referenced from: <EF637EE9-D02D-3F78-BF63-7297AE882DC6> /Users/aok/Projects/rustdev/MadeByMakepad/moxin/target/release/moxin-frontend
  Reason: tried: '/Users/aok/Projects/rustdev/MadeByMakepad/moxin/target/release/build/libsqlite3-sys-3e94e7c62bca9fd9/out/libwasmedge.0.dylib' (no such file), '/Users/aok/Projects/rustdev/MadeByMakepad/moxin/target/release/build/makepad-platform-7b118c87c8615420/out/libwasmedge.0.dylib' (no such file), '/Users/aok/Projects/rustdev/MadeByMakepad/moxin/target/release/build/ring-bf6cd0fc8c607364/out/libwasmedge.0.dylib' (no such file), '/Users/aok/Projects/rustdev/MadeByMakepad/moxin/target/release/deps/libwasmedge.0.dylib' (no such file), '/Users/aok/Projects/rustdev/MadeByMakepad/moxin/target/release/libwasmedge.0.dylib' (no such file), '/Users/aok/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libwasmedge.0.dylib' (no such file), '/Users/aok/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/libwasmedge.0.dylib' (no such file), '/Users/aok/lib/libwasmedge.0.dylib' (no such file), '/usr/local/lib/libwasmedge.0.dylib' (no such file), '/usr/lib/libwasmedge.0.dylib' (no such file, not in dyld cache)
Abort trap: 6

I have wasmedge installed
>$ wasmedge -v
wasmedge version 0.13.5

**Comment by L-jasmine** [comment]
Hello, has this issue been resolved? If not, could you please provide the installation path for your WasmEdge?

**Comment by andodeki** [comment]
Hello @L-jasmine its still not resolved
this is the installation path
/Users/aok/.wasmedge/bin/wasmedge

**Comment by L-jasmine** [comment]
@andodeki try
`export LD_LIBRARY_PATH=/Users/aok/.wasmedge/lib`
or
`export LD_LIBRARY_PATH=/Users/aok/.wasmedge/lib64`

**Comment by andodeki** [comment]
Still the same error

**Comment by L-jasmine** [comment]
Can you find libwasmedge.dylib in ~/.wasmedge or its subdirectories?

**Comment by andodeki** [comment]
yeah
`$ ls /Users/aok/.wasmedge/lib
libwasmedge.0.0.3.dylib	libwasmedge.0.dylib	libwasmedge.dylib
libwasmedge.0.0.3.tbd	libwasmedge.0.tbd	libwasmedge.tbd`

**Comment by L-jasmine** [comment]
Doesn't this work?
`export LD_LIBRARY_PATH=/Users/aok/.wasmedge/lib`

**Comment by L-jasmine** [comment]
try this
`export DYLD_LIBRARY_PATH=/Users/aok/.wasmedge/lib`
On macOS, it should be DYLD_LIBRARY_PATH.

**Comment by L-jasmine** [comment]
sorry, I don't have a macOS system. I'll find someone else to help you take a look.

**Comment by andodeki** [comment]
i decided to link
`ln -s /Users/aok/.wasmedge/lib/* /usr/local/lib/
`
